---
driver:
  name: vagrant
  customize:
    memory: 512

verifier:
  name: inspec

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.11.18

platforms:
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: harden
    run_list:
      - recipe[base_hardening::default]
