name 'base_hardening'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures base_hardening'
long_description 'Installs/Configures base_hardening'
version '0.1.0'
