name 'base_hardening'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures base_hardening'
long_description 'Installs/Configures base_hardening'
version '0.2.0'

depends 'openssh', '~> 2.0.0'
depends 'sysctl', '~> 0.6.0'
